# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, unique=True, verbose_name='produto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'verbose_name': 'produto',
                'ordering': ['category', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='produto')),
            ],
            options={
                'verbose_name_plural': 'cotações',
                'verbose_name': 'cotação',
                'ordering': ['product__product'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50, verbose_name='loja')),
            ],
            options={
                'verbose_name_plural': 'lojas',
                'verbose_name': 'loja',
                'ordering': ['store'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='loja'),
        ),
    ]
